MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
MAX_FIRST_NAME_LENGTH = 150
MAX_LAST_NAME_LENGTH = 150
MAX_RECIPE_NAME_LENGTH = 256
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_MEASUREMENT_UNIT_LENGTH = 64

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 2147483647

DEFAULT_PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = "limit"
RECIPES_LIMIT_QUERY_PARAM = "recipes_limit"

SHORT_CODE_LENGTH = 6
SHORT_LINK_URL_NAME = "recipe-short-link"

SHOPPING_LIST_FILENAME = "shopping-list.txt"
SHOPPING_LIST_HEADER = "Список покупок"
